"""Schema inicial da API; não altera as tabelas da branch legada."""
from alembic import op
import sqlalchemy as sa
revision = "0001_api"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_localidades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('chave', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('api_projetos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('arquivo', sa.Text(), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=40), nullable=False),
    sa.Column('projetista', sa.Text(), nullable=False),
    sa.Column('responsavel_implantacao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('api_importacoes_legadas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('nome_arquivo', sa.Text(), nullable=False),
    sa.Column('original', sa.JSON(), nullable=False),
    sa.Column('avisos', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['api_projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('api_itens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('localidade_id', sa.String(length=36), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('local_origem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('serial', sa.Text(), nullable=False),
    sa.Column('origem', sa.Text(), nullable=False),
    sa.Column('responsavel', sa.Text(), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('revisao', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('nao_separado','separado','outro_local','sem_estoque')", name='item_status'),
    sa.CheckConstraint('quantidade IS NULL OR quantidade > 0', name='item_quantidade_positiva'),
    sa.ForeignKeyConstraint(['localidade_id'], ['api_localidades.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['api_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_itens_localidade_id'), 'api_itens', ['localidade_id'], unique=False)
    op.create_index(op.f('ix_api_itens_projeto_id'), 'api_itens', ['projeto_id'], unique=False)
    op.create_table('api_remessas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('localidade_id', sa.String(length=36), nullable=False),
    sa.Column('origem_expedicao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('nf', sa.Text(), nullable=False),
    sa.Column('nf_solicitada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_entrega_logistica', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('rascunho','nf_solicitada','nf_registrada','entregue_logistica','cancelada','legado_revisar')", name='remessa_status'),
    sa.ForeignKeyConstraint(['localidade_id'], ['api_localidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_remessas_localidade_id'), 'api_remessas', ['localidade_id'], unique=False)
    op.create_table('api_remessa_itens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('remessa_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='remessa_item_quantidade_positiva'),
    sa.ForeignKeyConstraint(['item_id'], ['api_itens.id'], ),
    sa.ForeignKeyConstraint(['remessa_id'], ['api_remessas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remessa_id', 'item_id')
    )
    op.create_index(op.f('ix_api_remessa_itens_item_id'), 'api_remessa_itens', ['item_id'], unique=False)
    op.create_index(op.f('ix_api_remessa_itens_remessa_id'), 'api_remessa_itens', ['remessa_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_remessa_itens_remessa_id'), table_name='api_remessa_itens')
    op.drop_index(op.f('ix_api_remessa_itens_item_id'), table_name='api_remessa_itens')
    op.drop_table('api_remessa_itens')
    op.drop_index(op.f('ix_api_remessas_localidade_id'), table_name='api_remessas')
    op.drop_table('api_remessas')
    op.drop_index(op.f('ix_api_itens_projeto_id'), table_name='api_itens')
    op.drop_index(op.f('ix_api_itens_localidade_id'), table_name='api_itens')
    op.drop_table('api_itens')
    op.drop_table('api_importacoes_legadas')
    op.drop_table('api_projetos')
    op.drop_table('api_localidades')
    # ### end Alembic commands ###
